epochs: 601
MODEL:
    framework: "Distillation"
    teacher_model:
        name: "Vgg16"
        pretrained: "./vgg16"
    student_model:
        name: "small_VGG"
    loss_cfg:
        name: "MseDirectionLoss"
        lamda: 0.5

DATASET:
    batch_size: 64
    num_worker: 8
    normal_class: "capsule"
    train:
        name: "ImageFolder"
        dataset_root: "/Users/alex/Downloads/MVTec/capsule/train"
    test:
        name: "ImageFolder"
        dataset_root: "/Users/alex/Downloads/MVTec/capsule/test"

PIPELINE:
    train:
        transform:
            - Resize:
                  size: [128, 128]
                  interpolation: "bilinear"

OPTIMIZER: #OPTIMIZER field
    name: "Adam"
    beta1: 0.9
    beta2: 0.999
    lr: 1e-3
